
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.146.200.93:3306/online_education
    username: root
    password: Aa112233#

  redis:
    database: 0
    host: 8.146.200.93
    port: 6379
    password: Aa112233#
    timeout: 5s
    connect-timeout: 5s
server:
  port: 8888

# Sa-Token配置
sa-token:
  token-name: token  # token名称 (同时也是cookie名称)
  timeout: 2592000
  activity-timeout: 86400
  is-concurrent: true  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-share: false  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  token-style: uuid
  is-log: false
  jwt-secret-key: onlineEducationTokenKey